# Parte 1 - Baseline RAG funcional

## Nombres: Jessica Ballesteros, Miguel Álvarez, Darlyn Ludeña

**Implementa el pipeline sobre tu corpus, a partir del Lab-02 del día miércoles:**

In [37]:
import socket
import sys
from pathlib import Path
import sys
import os
from rag_pipeline import RagPipeline
from qdrant_client import QdrantClient
import pandas as pd
import json

In [11]:

# Buscar la raíz del proyecto
raiz = Path.cwd()

while raiz != raiz.parent:
    if (
        (raiz / "pyproject.toml").exists()
        and (raiz / "rag_pipeline.py").exists()
    ):
        break
    raiz = raiz.parent

ROOT = raiz

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

print("Raíz del proyecto:", ROOT)
print("rag_pipeline.py:", (ROOT / "rag_pipeline.py").exists())
print("pyproject.toml:", (ROOT / "pyproject.toml").exists())

Raíz del proyecto: /home/dludena/taller-02-rag-alvarez-ballesteros-ludena
rag_pipeline.py: True
pyproject.toml: True

In [ ]:
# Configuración de la Parte 1

os.environ["EMBEDDING_BACKEND"] = "h200"

# Qdrant NO debe ser :memory: en la Parte 1
os.environ["QDRANT_URL"] = "http://localhost:6333"

# Colección específica del baseline
os.environ["QDRANT_COLLECTION"] = "mmia6013_rag_baseline"

# Corpus real
os.environ["CORPUS_DIR"] = str(ROOT / "corpus")

os.environ["OLLAMA_URL"] = "http://localhost:11434"

print("EMBEDDING_BACKEND:", os.environ["EMBEDDING_BACKEND"])
print("QDRANT_URL:", os.environ["QDRANT_URL"])
print("CORPUS_DIR:", os.environ["CORPUS_DIR"])

EMBEDDING_BACKEND: h200
QDRANT_URL: http://localhost:6333
CORPUS_DIR: /home/dludena/taller-02-rag-alvarez-ballesteros-ludena/corpus

In [13]:


cliente_qdrant = QdrantClient(
    url=os.environ["QDRANT_URL"]
)

print("Colecciones existentes:")
print(cliente_qdrant.get_collections())

Colecciones existentes:
collections=[]

In [14]:
print("Host:", socket.gethostname())

Host: DGX-H200-USFQ

In [15]:
pipeline = RagPipeline(
    collection="mmia6013_rag_baseline"
)

print("Backend:", os.environ["EMBEDDING_BACKEND"])
print("Modelo:", pipeline.encoder.modelo if hasattr(pipeline.encoder, "modelo") else "bge-m3")
print("Tope del modelo:", pipeline.max_seq_tokens)
print("Colección:", pipeline.collection)

/opt/datadog-packages/datadog-apm-library-python/4.11.1/ddtrace_pkgs/site-packages-ddtrace-py3.12-manylinux2014-x86_64/ddtrace/internal/module.py:314: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  self.loader.exec_module(module)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Backend: h200
Modelo: bge-m3
Tope del modelo: 8192
Colección: mmia6013_rag_baseline

#### 1. Ingesta. Parsea los documentos (PDF → texto). Documenta qué se pierde o se degrada (tablas, encabezados,pies de página) y qué documentos, si alguno, la ingesta rechazó por no tener texto útil.

In [16]:
corpus_dir = ROOT / "corpus"

print("Corpus:", corpus_dir)
print("¿Existe?:", corpus_dir.exists())
print("¿Es carpeta?:", corpus_dir.is_dir())

documentos = sorted(corpus_dir.glob("*"))

print("\nDocumentos encontrados:")
for doc in documentos:
    print(" -", doc.name)

Corpus: /home/dludena/taller-02-rag-alvarez-ballesteros-ludena/corpus
¿Existe?: True
¿Es carpeta?: True

Documentos encontrados:
 - .gitkeep
 - bai-2022-constitutional-ai.pdf
 - brown-2020-gpt3.pdf
 - ouyang-2022-instructgpt.pdf
 - rafailov-2023-dpo.pdf
 - vaswani-2017-attention-is-all-you-need.pdf
 - wei-2022-chain-of-thought.pdf

In [17]:
chunks = pipeline.ingest(
    corpus_dir,
    chunk_tokens=512,
    overlap_tokens=102
)

print(f"\nFragmentos obtenidos: {len(chunks)}")

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (30809 > 8192). Running this sequence through the model will result in indexing errors

ingesta: bai-2022-constitutional-ai.pdf: 34 página(s), 94294 caracteres útiles → 75 fragmento(s)
ingesta: brown-2020-gpt3.pdf: 75 página(s), 186342 caracteres útiles → 156 fragmento(s)
ingesta: ouyang-2022-instructgpt.pdf: 68 página(s), 143167 caracteres útiles → 118 fragmento(s)
ingesta: rafailov-2023-dpo.pdf: 27 página(s), 71700 caracteres útiles → 66 fragmento(s)
ingesta: vaswani-2017-attention-is-all-you-need.pdf: 15 página(s), 31566 caracteres útiles → 25 fragmento(s)
ingesta: wei-2022-chain-of-thought.pdf: 43 página(s), 105503 caracteres útiles → 90 fragmento(s)

Fragmentos obtenidos: 530

In [ ]:


datos_chunks = []

for chunk in chunks:
    datos_chunks.append({
        "chunk_id": chunk.id,
        "documento": chunk.document,
        "chunk_index": chunk.chunk_index,
        "tokens": len(
            pipeline.encoder.tokenizer(
                chunk.text,
                add_special_tokens=False,
                truncation=False
            )["input_ids"]
        ),
        "texto": chunk.text
    })

df_chunks = pd.DataFrame(datos_chunks)
print("Total chunks:", len(df_chunks))

,chunk_id,documento,chunk_index,tokens,texto
0,bai-2022-constitutional-ai-0000,bai-2022-constitutional-ai.pdf,0,512,[page=1] Constitutional AI: Harmlessness from ...
1,bai-2022-constitutional-ai-0001,bai-2022-constitutional-ai.pdf,1,512,"from the finetuned model, use a model to evalu..."
2,bai-2022-constitutional-ai-0002,bai-2022-constitutional-ai.pdf,2,510,"(RL) stage, shown as the sequence of steps at ..."
3,bai-2022-constitutional-ai-0003,bai-2022-constitutional-ai.pdf,3,512,"ying a general AI system, we cannot avoid choo..."
4,bai-2022-constitutional-ai-0004,bai-2022-constitutional-ai.pdf,4,512,+ Harmless Figure 2 We show harmlessness versu...

Total chunks: 530

In [20]:
df_chunks.head()

,chunk_id,documento,chunk_index,tokens,texto
0,bai-2022-constitutional-ai-0000,bai-2022-constitutional-ai.pdf,0,512,[page=1] Constitutional AI: Harmlessness from ...
1,bai-2022-constitutional-ai-0001,bai-2022-constitutional-ai.pdf,1,512,"from the finetuned model, use a model to evalu..."
2,bai-2022-constitutional-ai-0002,bai-2022-constitutional-ai.pdf,2,510,"(RL) stage, shown as the sequence of steps at ..."
3,bai-2022-constitutional-ai-0003,bai-2022-constitutional-ai.pdf,3,512,"ying a general AI system, we cannot avoid choo..."
4,bai-2022-constitutional-ai-0004,bai-2022-constitutional-ai.pdf,4,512,+ Harmless Figure 2 We show harmlessness versu...

In [21]:
carpeta_resultados = ROOT / "resultados" / "parte1"
carpeta_resultados.mkdir(parents=True, exist_ok=True)

archivo_chunks = carpeta_resultados / "numeral1.csv"

df_chunks.to_csv(
    archivo_chunks,
    index=False,
    encoding="utf-8-sig"
)

print(f"Guardado en: {archivo_chunks}")

Guardado en: /home/dludena/taller-02-rag-alvarez-ballesteros-ludena/resultados/parte1/numeral1.csv

### 2. Fragmentación. Baseline de tamaño fijo con solapamiento, en tokens del modelo de embeddings, con `chunk_tokens` y  `overlap_tokens` explícitos. El tope de bge-m3 es 8192 y el  Lab-02 del día miércoles corta por defecto en 512: la justificación dice por qué tu tamaño sirve a tus preguntas, no solo que cabe.

In [22]:
CHUNK_TOKENS = 512
OVERLAP_TOKENS = 102

print("Parámetros de fragmentación")
print("chunk_tokens:", CHUNK_TOKENS)
print("overlap_tokens:", OVERLAP_TOKENS)
print("máximo bge-m3:", pipeline.max_seq_tokens)

Parámetros de fragmentación
chunk_tokens: 512
overlap_tokens: 102
máximo bge-m3: 8192

Se utiliza un tamaño de 512 tokens con 102 tokens de solapamiento. Este tamaño sigue el baseline propuesto por el Lab-02 y mantiene los fragmentos suficientemente por debajo del límite de 8192 tokens de bge-m3. El solapamiento permite conservar parte del contexto cuando una idea se encuentra cerca del límite entre dos fragmentos. La elección será evaluada posteriormente mediante el golden set, por lo que no se asume de antemano que 512 sea óptimo.

Se utiliza un tamaño de 512 tokens con 102 tokens de solapamiento,
siguiendo el tamaño baseline establecido en el Lab-02. Para este corpus,
un fragmento de 512 tokens permite recuperar una unidad de contenido
suficientemente amplia para responder preguntas conceptuales sobre los
papers, manteniendo una granularidad adecuada para distinguir diferentes
temas dentro de un mismo documento. El solapamiento de 102 tokens
(aproximadamente 20 %) permite conservar contexto cuando una idea o
explicación queda dividida entre dos fragmentos. El tamaño se mantiene
muy por debajo del límite de 8192 tokens de bge-m3, pero esta condición
solo garantiza que el fragmento pueda ser procesado; la elección final
será evaluada posteriormente con el golden set mediante Hit Rate y MRR.

###  3. Embedding e indexación. Con bge-m3 en la H200 (EMBEDDING_BACKEND=h200, el valor por defecto, con GlobalProtect conectada) o, sin VPN, con OpenAI (EMBEDDING_BACKEND=openai). Declara en el informe la fila por su id y con su verified_at. Indexa en Qdrant (el contenedor, no :memory:, que es solo para depurar).

In [23]:
pipeline.index(chunks)

print("Índice creado correctamente.")
print("Colección:", pipeline.collection)
print("Número de chunks indexados:", len(chunks))

Índice creado correctamente.
Colección: mmia6013_rag_baseline
Número de chunks indexados: 530

In [25]:
info = cliente_qdrant.get_collection(
    collection_name=pipeline.collection
)

print(info)

status=<CollectionStatus.GREEN: 'green'> optimizer_status=<OptimizersStatusOneOf.OK: 'ok'> warnings=None indexed_vectors_count=0 points_count=530 segments_count=8 config=CollectionConfig(params=CollectionParams(vectors=VectorParams(size=1024, distance=<Distance.COSINE: 'Cosine'>, hnsw_config=None, quantization_config=None, on_disk=None, memory=None, datatype=None, multivector_config=None), shard_number=1, sharding_method=None, replication_factor=1, write_consistency_factor=1, read_fan_out_factor=None, read_fan_out_delay_ms=None, on_disk_payload=True, payload=None, sparse_vectors=None), hnsw_config=HnswConfig(m=16, ef_construct=100, full_scan_threshold=10000, max_indexing_threads=0, on_disk=False, memory=None, payload_m=None, inline_storage=None), optimizer_config=OptimizersConfig(deleted_threshold=0.2, vacuum_min_vector_number=1000, default_segment_number=0, max_segment_size=None, memmap_threshold=None, indexing_threshold=10000, flush_interval_sec=5, max_optimization_threads=None, prevent_unoptimized=None), wal_config=WalConfig(wal_capacity_mb=32, wal_segments_ahead=0, wal_retain_closed=1), quantization_config=None, strict_mode_config=None, metadata=None) payload_schema={} update_queue=UpdateQueueInfo(length=0, deferred_points=None)

In [26]:
cantidad = cliente_qdrant.count(
    collection_name=pipeline.collection,
    exact=True
)

print("Vectores en Qdrant:", cantidad.count)

Vectores en Qdrant: 530

In [27]:
df_embedding = pd.DataFrame([{
    "id": "embed_local_multilingue",
    "proveedor": "BAAI",
    "modelo": "BAAI/bge-m3",
    "dimension": 1024,
    "tokens_secuencia": 8192,
    "multilingue": True,
    "costo_usd_1M": 0,
    "verified_at": "2026-08-27"
}])

display(df_embedding)

,id,proveedor,modelo,dimension,tokens_secuencia,multilingue,costo_usd_1M,verified_at
0,embed_local_multilingue,BAAI,BAAI/bge-m3,1024,8192,True,0,2026-08-27

In [28]:
archivo_embedding = carpeta_resultados / "numeral3_embedding_baseline.csv"

df_embedding.to_csv(
    archivo_embedding,
    index=False,
    encoding="utf-8-sig"
)

print(f"Guardado en: {archivo_embedding}")

Guardado en: /home/dludena/taller-02-rag-alvarez-ballesteros-ludena/resultados/parte1/numeral3_embedding_baseline.csv

### 4. Recuperación. Muestra los top-5 fragmentos para al menos 3 preguntas de prueba, con documento y puntaje.

In [39]:
preguntas_prueba = [
    "What are the main advantages of the Transformer architecture compared with recurrent and convolutional neural networks for sequence transduction?",

    "How does GPT-3 demonstrate that increasing model size and using in-context learning can improve few-shot performance?",

    "How does InstructGPT use human feedback to improve the alignment of language models with user intentions?"
]

In [40]:
resultados_retrieval = []

for pregunta in preguntas_prueba:

    resultados = pipeline.retrieve(
        pregunta,
        top_k=5
    )

    print("=" * 100)
    print("PREGUNTA:")
    print(pregunta)
    print("\nTOP 5 VECINOS:\n")

    for rank, resultado in enumerate(resultados, start=1):

        print(f"--- Vecino {rank} ---")
        print(f"Score:     {resultado['score']:.4f}")
        print(f"Documento: {resultado['document']}")
        print(f"Chunk ID:  {resultado['chunk_id']}")
        print(f"Texto:    {resultado['text']}")
        print()

        resultados_retrieval.append({
            "pregunta": pregunta,
            "rank": rank,
            "score": resultado["score"],
            "documento": resultado["document"],
            "chunk_id": resultado["chunk_id"],
            "texto": resultado["text"]
        })

====================================================================================================
PREGUNTA:
What are the main advantages of the Transformer architecture compared with recurrent and convolutional neural networks for sequence transduction?

TOP 5 VECINOS:

--- Vecino 1 ---
Score:     0.6861
Documento: vaswani-2017-attention-is-all-you-need.pdf
Chunk ID:  vaswani-2017-attention-is-all-you-need-0003
Texto:    it more difficult to learn dependencies between distant positions [ 12]. In the Transformer this is reduced to a constant number of operations, albeit at the cost of reduced effective resolution due to averaging attention-weighted positions, an effect we counteract with Multi-Head Attention as described in section 3.2. Self-attention, sometimes called intra-attention is an attention mechanism relating different positions of a single sequence in order to compute a representation of the sequence. Self-attention has been used successfully in a variety of tasks including reading comprehension, abstractive summarization, textual entailment and learning task-independent sentence representations [4, 27, 28, 22]. End-to-end memory networks are based on a recurrent attention mechanism instead of sequence- aligned recurrence and have been shown to perform well on simple-language question answering and language modeling tasks [34]. To the best of our knowledge, however, the Transformer is the first transduction model relying entirely on self-attention to compute representations of its input and output without using sequence- aligned RNNs or convolution. In the following sections, we will describe the Transformer, motivate self-attention and discuss its advantages over models such as [17, 18] and [9]. 3 Model Architecture Most competitive neural sequence transduction models have an encoder-decoder structure [5, 2, 35]. Here, the encoder maps an input sequence of symbol representations (x1,...,x n) to a sequence of continuous representations z = (z1,...,z n). Given z, the decoder then generates an output sequence (y1,...,y m) of symbols one element at a time. At each step the model is auto-regressive [10], consuming the previously generated symbols as additional input when generating the next. 2 [page=3] Figure 1: The Transformer - model architecture. The Transformer follows this overall architecture using stacked self-attention and point-wise, fully connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1, respectively. 3.1 Enco

--- Vecino 2 ---
Score:     0.6700
Documento: vaswani-2017-attention-is-all-you-need.pdf
Chunk ID:  vaswani-2017-attention-is-all-you-need-0002
Texto:    they generate a sequence of hidden statesht, as a function of the previous hidden stateht−1 and the input for positiont. This inherently sequential nature precludes parallelization within training examples, which becomes critical at longer sequence lengths, as memory constraints limit batching across examples. Recent work has achieved significant improvements in computational efficiency through factorization tricks [21] and conditional computation [32], while also improving model performance in case of the latter. The fundamental constraint of sequential computation, however, remains. Attention mechanisms have become an integral part of compelling sequence modeling and transduc- tion models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences [2, 19]. In all but a few cases [27], however, such attention mechanisms are used in conjunction with a recurrent network. In this work we propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism to draw global dependencies between input and output. The Transformer allows for significantly more parallelization and can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs. 2 Background The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU [16], ByteNet [18] and ConvS2S [9], all of which use convolutional neural networks as basic building block, computing hidden representations in parallel for all input and output positions. In these models, the number of operations required to relate signals from two arbitrary input or output positions grows in the distance between positions, linearly for ConvS2S and logarithmically for ByteNet. This makes it more difficult to learn dependencies between distant positions [ 12]. In the Transformer this is reduced to a constant number of operations, albeit at the cost of reduced effective resolution due to averaging attention-weighted positions, an effect we counteract with Multi-Head Attention as described in section 3.2. Self-attention, sometimes called intra-attention is an attention mechanism relating different positions of a single sequence in order to compute a

--- Vecino 3 ---
Score:     0.6643
Documento: vaswani-2017-attention-is-all-you-need.pdf
Chunk ID:  vaswani-2017-attention-is-all-you-need-0017
Texto:    . During inference, we 9 [page=10] Table 4: The Transformer generalizes well to English constituency parsing (Results are on Section 23 of WSJ) Parser Training WSJ 23 F1 Vinyals & Kaiser el al. (2014) [37] WSJ only, discriminative 88.3 Petrov et al. (2006) [29] WSJ only, discriminative 90.4 Zhu et al. (2013) [40] WSJ only, discriminative 90.4 Dyer et al. (2016) [8] WSJ only, discriminative 91.7 Transformer (4 layers) WSJ only, discriminative 91.3 Zhu et al. (2013) [40] semi-supervised 91.3 Huang & Harper (2009) [14] semi-supervised 91.3 McClosky et al. (2006) [26] semi-supervised 92.1 Vinyals & Kaiser el al. (2014) [37] semi-supervised 92.1 Transformer (4 layers) semi-supervised 92.7 Luong et al. (2015) [23] multi-task 93.0 Dyer et al. (2016) [8] generative 93.3 increased the maximum output length to input length + 300. We used a beam size of 21 andα = 0.3 for both WSJ only and the semi-supervised setting. Our results in Table 4 show that despite the lack of task-specific tuning our model performs sur- prisingly well, yielding better results than all previously reported models with the exception of the Recurrent Neural Network Grammar [8]. In contrast to RNN sequence-to-sequence models [37], the Transformer outperforms the Berkeley- Parser [29] even when training only on the WSJ training set of 40K sentences. 7 Conclusion In this work, we presented the Transformer, the first sequence transduction model based entirely on attention, replacing the recurrent layers most commonly used in encoder-decoder architectures with multi-headed self-attention. For translation tasks, the Transformer can be trained significantly faster than architectures based on recurrent or convolutional layers. On both WMT 2014 English-to-German and WMT 2014 English-to-French translation tasks, we achieve a new state of the art. In the former task our best model outperform

--- Vecino 4 ---
Score:     0.6364
Documento: vaswani-2017-attention-is-all-you-need.pdf
Chunk ID:  vaswani-2017-attention-is-all-you-need-0018
Texto:    recurrent layers most commonly used in encoder-decoder architectures with multi-headed self-attention. For translation tasks, the Transformer can be trained significantly faster than architectures based on recurrent or convolutional layers. On both WMT 2014 English-to-German and WMT 2014 English-to-French translation tasks, we achieve a new state of the art. In the former task our best model outperforms even all previously reported ensembles. We are excited about the future of attention-based models and plan to apply them to other tasks. We plan to extend the Transformer to problems involving input and output modalities other than text and to investigate local, restricted attention mechanisms to efficiently handle large inputs and outputs such as images, audio and video. Making generation less sequential is another research goals of ours. The code we used to train and evaluate our models is available at https://github.com/ tensorflow/tensor2tensor. Acknowledgements We are grateful to Nal Kalchbrenner and Stephan Gouws for their fruitful comments, corrections and inspiration. References [1] Jimmy Lei Ba, Jamie Ryan Kiros, and Geoffrey E Hinton. Layer normalization. arXiv preprint arXiv:1607.06450, 2016. [2] Dzmitry Bahdanau, Kyunghyun Cho, and Yoshua Bengio. Neural machine translation by jointly learning to align and translate. CoRR, abs/1409.0473, 2014. [3] Denny Britz, Anna Goldie, Minh-Thang Luong, and Quoc V. Le. Massive exploration of neural machine translation architectures. CoRR, abs/1703.03906, 2017. [4] Jianpeng Cheng, Li Dong, and Mirella Lapata. Long short-term memory-networks for machine reading. arXiv preprint arXiv:1601.06733, 2016. 10 [page=11] [5] Kyunghyun Cho, Bart van Merrienboer, Caglar Gulcehre, Fethi Bougares, Holger Schwenk, and Yoshua Bengio. Learning phrase representations using rnn encoder-decoder for statistical machine translation. CoRR, abs/1406.1078, 2014. [6] Francois Chollet. X

--- Vecino 5 ---
Score:     0.6358
Documento: vaswani-2017-attention-is-all-you-need.pdf
Chunk ID:  vaswani-2017-attention-is-all-you-need-0000
Texto:    [page=1] Provided proper attribution is provided, Google hereby grants permission to reproduce the tables and figures in this paper solely for use in journalistic or scholarly works. Attention Is All You Need Ashish Vaswani∗ Google Brain avaswani@google.com Noam Shazeer∗ Google Brain noam@google.com Niki Parmar∗ Google Research nikip@google.com Jakob Uszkoreit∗ Google Research usz@google.com Llion Jones∗ Google Research llion@google.com Aidan N. Gomez∗† University of Toronto aidan@cs.toronto.edu Łukasz Kaiser∗ Google Brain lukaszkaiser@google.com Illia Polosukhin∗‡ illia.polosukhin@gmail.com Abstract The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train. Our model achieves 28.4 BLEU on the WMT 2014 English- to-German translation task, improving over the existing best results, including ensembles, by over 2 BLEU. On the WMT 2014 English-to-French translation task, our model establishes a new single-model state-of-the-art BLEU score of 41.8 after training for 3.5 days on eight GPUs, a small fraction of the training costs of the best models from the literature. We show that the Transformer generalizes well to other tasks by applying it successfully to English constituency parsing both with large and limited training data. ∗Equal contribution. Listing order is random. Jakob proposed replacing RNNs with self-attention and started the effort to evaluate this idea. Ashish, with Illia, designed and implemented the first Transformer models and has been crucially involved in every aspect of this work. Noam proposed scaled dot-product attention, multi-head attention and the parameter-free position representation and became the

====================================================================================================
PREGUNTA:
How does GPT-3 demonstrate that increasing model size and using in-context learning can improve few-shot performance?

TOP 5 VECINOS:

--- Vecino 1 ---
Score:     0.7612
Documento: brown-2020-gpt3.pdf
Chunk ID:  brown-2020-gpt3-0010
Texto:    in-context learning abilities. Specifically, we evaluate GPT-3 on over two dozen NLP datasets, as well as several novel tasks designed to test rapid adaptation to tasks unlikely to be directly contained in the training set. For each task, we evaluate GPT-3 under 3 conditions: (a) “few-shot learning”, or in-context learning where we allow as many demonstrations as will fit into the model’s context window (typically 10 to 100), (b) “one-shot learning”, where we allow only one demonstration, and (c) “zero-shot” learning, where no demonstrations are allowed and only an instruction in natural language is given to the model. GPT-3 could also in principle be evaluated in the traditional fine-tuning setting, but we leave this to future work. Figure 1.2 illustrates the conditions we study, and shows few-shot learning of a simple task requiring the model to remove extraneous symbols from a word. Model performance improves with the addition of a natural language task description, and with the number of examples in the model’s context,K. Few-shot learning also improves dramatically with model size. Though the results in this case are particularly striking, the general trends with both model size and number of examples in-context hold for most tasks we study. We emphasize that these “learning” curves involve no gradient updates or fine-tuning, just increasing numbers of demonstrations given as conditioning. Broadly, on NLP tasks GPT-3 achieves promising results in the zero-shot and one-shot settings, and in the the few-shot setting is sometimes competitive with or even occasionally surpasses state-of-the-art (despite state-of-the-art being held by fine-tuned models). For example, GPT-3 achieves 81.5 F1 on CoQA in the zero-shot setting, 84.0 F1 on CoQA in the one-shot setting, 85.0 F1 in the few-shot setting. Similarly, GPT-3 achieves 64.3% accuracy on TriviaQA in the zero-shot setting, 68.0% in the one-shot setting, and 71.2% in the few-shot setting, the last of which is state-of-the

--- Vecino 2 ---
Score:     0.7317
Documento: brown-2020-gpt3.pdf
Chunk ID:  brown-2020-gpt3-0029
Texto:    PP+20]. GPT-3’s few-shot result further improves performance another 3.2% beyond this. On WebQuestions (WebQs), GPT-3 achieves 14.4% in the zero-shot setting, 25.3% in the one-shot setting, and 41.5% in the few-shot setting. This compares to 37.4% for fine-tuned T5-11B, and 44.7% for fine-tuned T5-11B+SSM, which uses a Q&A-specific pre-training procedure. GPT-3 in the few-shot setting approaches the performance of state-of-the-art fine-tuned models. Notably, compared to TriviaQA, WebQS shows a much larger gain from zero-shot to few-shot (and indeed its zero-shot and one-shot performance are poor), perhaps suggesting that the WebQs questions 13 [page=14] Figure 3.3: On TriviaQA GPT3’s performance grows smoothly with model size, suggesting that language models continue to absorb knowledge as their capacity increases. One-shot and few-shot performance make significant gains over zero-shot behavior, matching and exceeding the performance of the SOTA fine-tuned open-domain model, RAG [LPP+20] and/or the style of their answers are out-of-distribution for GPT-3. Nevertheless, GPT-3 appears able to adapt to this distribution, recovering strong performance in the few-shot setting. On Natural Questions (NQs) GPT-3 achieves 14.6% in the zero-shot setting, 23.0% in the one-shot setting, and 29.9% in the few-shot setting, compared to 36.6% for fine-tuned T5 11B+SSM. Similar to WebQS, the large gain from zero-shot to few-shot may suggest a distribution shift, and may also explain the less competitive performance compared to TriviaQA and WebQS. In particular, the questions in NQs tend towards very fine-grained knowledge on Wikipedia specifically which could be testing the limits of GPT-3’s capacity and broad pretraining distribution. Overall, on one of the three datasets GPT-3’s one-shot matches the open-domain fine-tuning SOTA. On the other two datasets it approaches the performance of the

--- Vecino 3 ---
Score:     0.7116
Documento: brown-2020-gpt3.pdf
Chunk ID:  brown-2020-gpt3-0009
Texto:    H+20]. Since in-context learning involves absorbing many skills and tasks within the parameters of the model, it is plausible that in-context learning abilities might show similarly strong gains with scale. 1In the context of language models this has sometimes been called “zero-shot transfer”, but this term is potentially ambiguous: the method is “zero-shot” in the sense that no gradient updates are performed, but it often involves providing inference-time demonstrations to the model, so is not truly learning from zero examples. To avoid this confusion, we use the term “meta-learning” to capture the inner-loop / outer-loop structure of the general method, and the term “in context-learning” to refer to the inner loop of meta-learning. We further specialize the description to “zero-shot”, “one-shot”, or “few-shot” depending on how many demonstrations are provided at inference time. These terms are intended to remain agnostic on the question of whether the model learns new tasks from scratch at inference time or simply recognizes patterns seen during training – this is an important issue which we discuss later in the paper, but “meta-learning” is intended to encompass both possibilities, and simply describes the inner-outer loop structure. 4 [page=5] Figure 1.3: Aggregate performance for all 42 accuracy-denominated benchmarks While zero-shot performance improves steadily with model size, few-shot performance increases more rapidly, demonstrating that larger models are more proficient at in-context learning. See Figure 3.8 for a more detailed analysis on SuperGLUE, a standard NLP benchmark suite. In this paper, we test this hypothesis by training a 175 billion parameter autoregressive language model, which we call GPT-3, and measuring its in-context learning abilities. Specifically, we evaluate GPT-3 on over two dozen NLP datasets, as well as several novel tasks designed to test rapid adaptation to tasks unlikely to be directly contained in the training set. For each task, we evaluate GPT-3 under 3 conditions: (a) “few-shot learning”, or in-context learning where we allow as many demonstrations as will fit into the model’s

--- Vecino 4 ---
Score:     0.7002
Documento: brown-2020-gpt3.pdf
Chunk ID:  brown-2020-gpt3-0016

In [41]:
df_retrieval = pd.DataFrame(resultados_retrieval)

display(df_retrieval)

,pregunta,rank,score,documento,chunk_id,texto
0,What are the main advantages of the Transforme...,1,0.686089,vaswani-2017-attention-is-all-you-need.pdf,vaswani-2017-attention-is-all-you-need-0003,it more difficult to learn dependencies betwee...
1,What are the main advantages of the Transforme...,2,0.670047,vaswani-2017-attention-is-all-you-need.pdf,vaswani-2017-attention-is-all-you-need-0002,"they generate a sequence of hidden statesht, a..."
2,What are the main advantages of the Transforme...,3,0.664278,vaswani-2017-attention-is-all-you-need.pdf,vaswani-2017-attention-is-all-you-need-0017,". During inference, we 9 [page=10] Table 4: Th..."
3,What are the main advantages of the Transforme...,4,0.636401,vaswani-2017-attention-is-all-you-need.pdf,vaswani-2017-attention-is-all-you-need-0018,recurrent layers most commonly used in encoder...
4,What are the main advantages of the Transforme...,5,0.635783,vaswani-2017-attention-is-all-you-need.pdf,vaswani-2017-attention-is-all-you-need-0000,[page=1] Provided proper attribution is provid...
5,How does GPT-3 demonstrate that increasing mod...,1,0.761181,brown-2020-gpt3.pdf,brown-2020-gpt3-0010,"in-context learning abilities. Specifically, w..."
6,How does GPT-3 demonstrate that increasing mod...,2,0.731738,brown-2020-gpt3.pdf,brown-2020-gpt3-0029,PP+20]. GPT-3’s few-shot result further improv...
7,How does GPT-3 demonstrate that increasing mod...,3,0.711648,brown-2020-gpt3.pdf,brown-2020-gpt3-0009,H+20]. Since in-context learning involves abso...
8,How does GPT-3 demonstrate that increasing mod...,4,0.700224,brown-2020-gpt3.pdf,brown-2020-gpt3-0016,"French. In this paper we focus on zero-shot, o..."
9,How does GPT-3 demonstrate that increasing mod...,5,0.690186,brown-2020-gpt3.pdf,brown-2020-gpt3-0011,"example, GPT-3 achieves 81.5 F1 on CoQA in the..."
10,How does InstructGPT use human feedback to imp...,1,0.780335,ouyang-2022-instructgpt.pdf,ouyang-2022-instructgpt-0000,[page=1] Training language models to follow in...
11,How does InstructGPT use human feedback to imp...,2,0.737397,ouyang-2022-instructgpt.pdf,ouyang-2022-instructgpt-0002,on a webpage from the internet—is different fr...
12,How does InstructGPT use human feedback to imp...,3,0.710870,ouyang-2022-instructgpt.pdf,ouyang-2022-instructgpt-0006,more work is needed to study how these models ...
13,How does InstructGPT use human feedback to imp...,4,0.699418,ouyang-2022-instructgpt.pdf,ouyang-2022-instructgpt-0042,on some inputs; we show some examples of this ...
14,How does InstructGPT use human feedback to imp...,5,0.699012,ouyang-2022-instructgpt.pdf,ouyang-2022-instructgpt-0005,InstructGPT shows small improvements in toxici...

In [42]:
archivo_retrieval = carpeta_resultados / "numeral4_retrieval_top5.csv"

df_retrieval.to_csv(
    archivo_retrieval,
    index=False,
    encoding="utf-8-sig"
)

print(f"Guardado en: {archivo_retrieval}")

Guardado en: /home/dludena/taller-02-rag-alvarez-ballesteros-ludena/resultados/parte1/numeral4_retrieval_top5.csv

### 5. Generación.`rag_pipeline.generate` ya trae la llamada: con la clave del curso usa la fila propietario_economico; sin clave, Ollama con open_weight_pequeno. El prompt del baseline hace tres cosas—delimita el contexto, obliga a usar solo el contexto y autoriza la abstención con una frase fija— y esa frase es la misma en el prompt, en el golden set y en el detector: ABSTENCION en cambiarla en los tres sitios

In [51]:
resultados_generacion = []

for pregunta in preguntas_prueba:

    resultado = pipeline.answer(
        pregunta,
        top_k=5
    )

    print("=" * 100)
    print("PREGUNTA:")
    print(pregunta)

    print("\nGENERADOR:")
    print(resultado["generator"])

    print("\nABSTENCIÓN:")
    print(resultado["abstained"])

    print("\nRESPUESTA:")
    print(resultado["answer"])

    print("\nPROMPT UTILIZADO:")
    print(resultado["prompt"])

    print()

    resultados_generacion.append({
        "pregunta": resultado["question"],
        "respuesta": resultado["answer"],
        "abstencion": resultado["abstained"],
        "generador": resultado["generator"],
        "prompt": resultado["prompt"]
    })

====================================================================================================
PREGUNTA:
What are the main advantages of the Transformer architecture compared with recurrent and convolutional neural networks for sequence transduction?

GENERADOR:
ollama:qwen3:32b

ABSTENCIÓN:
False

RESPUESTA:
El Transformer ofrece varias ventajas clave sobre modelos basados en redes recurrentes (RNN) o convolucionales (CNN) para transducción de secuencias:
1. **Mayor paralelización**: Al eliminar la dependencia secuencial de RNNs/CNNs, el Transformer permite un entrenamiento significativamente más rápido (sección 4 y abstracto).
2. **Dependencias globales sin restricciones de distancia**: A diferencia de CNNs (donde las operaciones crecen linealmente o logarítmicamente con la distancia entre posiciones), el Transformer relaciona posiciones arbitrarias en una secuencia con un número constante de operaciones, facilitando el aprendizaje de dependencias distantes (contexto 1 y 2).
3. **Superioridad en rendimiento**: Alcanza resultados de vanguardia en tareas como traducción (28.4 BLEU en WMT 2014 Inglés-Alemán, superando en 2 BLEU a modelos anteriores) y análisis sintáctico (92.7 F1 en WSJ) con menos recursos de entrenamiento (contexto 3 y 4).
4. **Uso exclusivo de mecanismos de atención**: Reemplaza RNNs/CNNs con atención autoregresiva (self-attention) y atención multi-cabeza, permitiendo representaciones globales sin recurrir a convoluciones o secuencias alineadas (contexto 1 y 5).

Estas ventajas se derivan del diseño basado en atención pura, que elimina las limitaciones de paralelización y resolución efectiva de modelos secuenciales tradicionales.

PROMPT UTILIZADO:
Responde usando solo el contexto recuperado.
Si el contexto no contiene la respuesta, di exactamente: "El corpus no contiene información suficiente."

Contexto:
[1] vaswani-2017-attention-is-all-you-need.pdf / vaswani-2017-attention-is-all-you-need-0003
it more difficult to learn dependencies between distant positions [ 12]. In the Transformer this is reduced to a constant number of operations, albeit at the cost of reduced effective resolution due to averaging attention-weighted positions, an effect we counteract with Multi-Head Attention as described in section 3.2. Self-attention, sometimes called intra-attention is an attention mechanism relating different positions of a single sequence in order to compute a representation of the sequence. Self-attention has been used successfully in a variety of tasks including reading comprehension, abstractive summarization, textual entailment and learning task-independent sentence representations [4, 27, 28, 22]. End-to-end memory networks are based on a recurrent attention mechanism instead of sequence- aligned recurrence and have been shown to perform well on simple-language question answering and language modeling tasks [34]. To the best of our knowledge, however, the Transformer is the first transduction model relying entirely on self-attention to compute representations of its input and output without using sequence- aligned RNNs or convolution. In the following sections, we will describe the Transformer, motivate self-attention and discuss its advantages over models such as [17, 18] and [9]. 3 Model Architecture Most competitive neural sequence transduction models have an encoder-decoder structure [5, 2, 35]. Here, the encoder maps an input sequence of symbol representations (x1,...,x n) to a sequence of continuous representations z = (z1,...,z n). Given z, the decoder then generates an output sequence (y1,...,y m) of symbols one element at a time. At each step the model is auto-regressive [10], consuming the previously generated symbols as additional input when generating the next. 2 [page=3] Figure 1: The Transformer - model architecture. The Transformer follows this overall architecture using stacked self-attention and point-wise, fully connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1, respectively. 3.1 Enco

[2] vaswani-2017-attention-is-all-you-need.pdf / vaswani-2017-attention-is-all-you-need-0002
they generate a sequence of hidden statesht, as a function of the previous hidden stateht−1 and the input for positiont. This inherently sequential nature precludes parallelization within training examples, which becomes critical at longer sequence lengths, as memory constraints limit batching across examples. Recent work has achieved significant improvements in computational efficiency through factorization tricks [21] and conditional computation [32], while also improving model performance in case of the latter. The fundamental constraint of sequential computation, however, remains. Attention mechanisms have become an integral part of compelling sequence modeling and transduc- tion models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences [2, 19]. In all but a few cases [27], however, such attention mechanisms are used in conjunction with a recurrent network. In this work we propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism to draw global dependencies between input and output. The Transformer allows for significantly more parallelization and can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs. 2 Background The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU [16], ByteNet [18] and ConvS2S [9], all of which use convolutional neural networks as basic building block, computing hidden representations in parallel for all input and output positions. In these models, the number of operations required to relate signals from two arbitrary input or output positions grows in the distance between positions, linearly for ConvS2S and logarithmically for ByteNet. This makes it more difficult to learn dependencies between distant positions [ 12]. In the Transformer this is reduced to a constant number of operations, albeit at the cost of reduced effective resolution due to averaging attention-weighted positions, an effect we counteract with Multi-Head Attention as described in section 3.2. Self-attention, sometimes called intra-attention is an attention mechanism relating different positions of a single sequence in order to compute a

[3] vaswani-2017-attention-is-all-you-need.pdf / vaswani-2017-attention-is-all-you-need-0017
. During inference, we 9 [page=10] Table 4: The Transformer generalizes well to English constituency parsing (Results are on Section 23 of WSJ) Parser Training WSJ 23 F1 Vinyals & Kaiser el al. (2014) [37] WSJ only, discriminative 88.3 Petrov et al. (2006) [29] WSJ only, discriminative 90.4 Zhu et al. (2013) [40] WSJ only, discriminative 90.4 Dyer et al. (2016) [8] WSJ only, discriminative 91.7 Transformer (4 layers) WSJ only, discriminative 91.3 Zhu et al. (2013) [40] semi-supervised 91.3 Huang & Harper (2009) [14] semi-supervised 91.3 McClosky et al. (2006) [26] semi-supervised 92.1 Vinyals & Kaiser el al. (2014) [37] semi-supervised 92.1 Transformer (4 layers) semi-supervised 92.7 Luong et al. (2015) [23] multi-task 93.0 Dyer et al. (2016) [8] generative 93.3 increased the maximum output length to input length + 300. We used a beam size of 21 andα = 0.3 for both WSJ only and the semi-supervised setting. Our results in Table 4 show that despite the lack of task-specific tuning our model performs sur- prisingly well, yielding better results than all previously reported models with the exception of the Recurrent Neural Network Grammar [8]. In contrast to RNN sequence-to-sequence models [37], the Transformer outperforms the Berkeley- Parser [29] even when training only on the WSJ training set of 40K sentences. 7 Conclusion In this work, we presented the Transformer, the first sequence transduction model based entirely on attention, replacing the recurrent layers most commonly used in encoder-decoder architectures with multi-headed self-attention. For translation tasks, the Transformer can be trained significantly faster than architectures based on recurrent or convolutional layers. On both WMT 2014 English-to-German and WMT 2014 English-to-French translation tasks, we achieve a new state of the art. In the former task our best model outperform

[4] vaswani-2017-attention-is-all-you-need.pdf / vaswani-2017-attention-is-all-you-need-0018
recurrent layers most commonly used in encoder-decoder architectures with multi-headed self-attention. For translation tasks, the Transformer can be trained significantly faster than architectures based on recurrent or convolutional layers. On both WMT 2014 English-to-German and WMT 2014 English-to-French translation tasks, we achieve a new state of the art. In the former task our best model outperforms even all previously reported ensembles. We are excited about the future of attention-based models and plan to apply them to other tasks. We plan to extend the Transformer to problems involving input and output modalities other than text and to investigate local, restricted attention mechanisms to efficiently handle large inputs and outputs such as images, audio and video. Making generation less sequential is another research goals of ours. The code we used to train and evaluate our models is available at https://github.com/ tensorflow/tensor2tensor. Acknowledgements We are grateful to Nal Kalchbrenner and Stephan Gouws for their fruitful comments, corrections and inspiration. References [1] Jimmy Lei Ba, Jamie Ryan Kiros, and Geoffrey E Hinton. Layer normalization. arXiv preprint arXiv:1607.06450, 2016. [2] Dzmitry Bahdanau, Kyunghyun Cho, and Yoshua Bengio. Neural machine translation by jointly learning to align and translate. CoRR, abs/1409.0473, 2014. [3] Denny Britz, Anna Goldie, Minh-Thang Luong, and Quoc V. Le. Massive exploration of neural machine translation architectures. CoRR, abs/1703.03906, 2017. [4] Jianpeng Cheng, Li Dong, and Mirella Lapata. Long short-term memory-networks for machine reading. arXiv preprint arXiv:1601.06733, 2016. 10 [page=11] [5] Kyunghyun Cho, Bart van Merrienboer, Caglar Gulcehre, Fethi Bougares, Holger Schwenk, and Yoshua Bengio. Learning phrase representations using rnn encoder-decoder for statistical machine translation. CoRR, abs/1406.1078, 2014. [6] Francois Chollet. X

[5] vaswani-2017-attention-is-all-you-need.pdf / vaswani-2017-attention-is-all-you-need-0000
[page=1] Provided proper attribution is provided, Google hereby grants permission to reproduce the tables and figures in this paper solely for use in journalistic or scholarly works. Attention Is All You Need Ashish Vaswani∗ Google Brain avaswani@google.com Noam Shazeer∗ Google Brain noam@google.com Niki Parmar∗ Google Research nikip@google.com Jakob Uszkoreit∗ Google Research usz@google.com Llion Jones∗ Google Research llion@google.com Aidan N. Gomez∗† University of Toronto aidan@cs.toronto.edu Łukasz Kaiser∗ Google Brain lukaszkaiser@google.com Illia Polosukhin∗‡ illia.polosukhin@gmail.com Abstract The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train. Our model achieves 28.4 BLEU on the WMT 2014 English- to-German translation task, improving over the existing best results, including ensembles, by over 2 BLEU. On the WMT 2014 English-to-French translation task, our model establishes a new single-model state-of-the-art BLEU score of 41.8 after training for 3.5 days on eight GPUs, a small fraction of the training costs of the best models from the literature. We show that the Transformer generalizes well to other tasks by applying it successfully to English constituency parsing both with large and limited training data. ∗Equal contribution. Listing order is random. Jakob proposed replacing RNNs with self-attention and started the effort to evaluate this idea. Ashish, with Illia, designed and implemented the first Transformer models and has been crucially involved in every aspect of this work. Noam proposed scaled dot-product attention, multi-head attention and the parameter-free position representation and became the

Pregunta: What are the main advantages of the Transformer architecture compared with recurrent and convolutional neural networks for sequence transduction?
Respuesta:

====================================================================================================
PREGUNTA:
How does GPT-3 demonstrate that increasing model size and using in-context learning can improve few-shot performance?

GENERADOR:
ollama:qwen3:32b

ABSTENCIÓN:
False

RESPUESTA:
GPT-3 demuestra que aumentar el tamaño del modelo y utilizar el aprendizaje en contexto mejora el desempeño en escenarios de *few-shot* mediante pruebas en múltiples tareas NLP. Según el contexto, el desempeño en *few-shot* mejora drásticamente con el tamaño del modelo, como se observa en tareas como CoQA (85.0 F1 en *few-shot* vs. 81.5 F1 en *zero-shot*) y TriviaQA (71.2% en *few-shot* vs. 64.3% en *zero-shot*), donde los resultados en *few-shot* superan o igualan a modelos finetunados. Además, el texto indica que "el desempeño en *few-shot* aumenta más rápidamente con el tamaño del modelo", lo que sugiere que modelos más grandes son más eficientes en el aprendizaje a partir de ejemplos proporcionados en el contexto (ver [1] y [3]). Esto se complementa con la observación de que el número de ejemplos en el contexto y el tamaño del modelo tienen un impacto positivo conjunto, sin necesidad de actualizaciones de gradientes.

PROMPT UTILIZADO:
Responde usando solo el contexto recuperado.
Si el contexto no contiene la respuesta, di exactamente: "El corpus no contiene información suficiente."

Contexto:
[1] brown-2020-gpt3.pdf / brown-2020-gpt3-0010
in-context learning abilities. Specifically, we evaluate GPT-3 on over two dozen NLP datasets, as well as several novel tasks designed to test rapid adaptation to tasks unlikely to be directly contained in the training set. For each task, we evaluate GPT-3 under 3 conditions: (a) “few-shot learning”, or in-context learning where we allow as many demonstrations as will fit into the model’s context window (typically 10 to 100), (b) “one-shot learning”, where we allow only one demonstration, and (c) “zero-shot” learning, where no demonstrations are allowed and only an instruction in natural language is given to the model. GPT-3 could also in principle be evaluated in the traditional fine-tuning setting, but we leave this to future work. Figure 1.2 illustrates the conditions we study, and shows few-shot learning of a simple task requiring the model to remove extraneous symbols from a word. Model performance improves with the addition of a natural language task description, and with the number of examples in the model’s context,K. Few-shot learning also improves dramatically with model size. Though the results in this case are particularly striking, the general trends with both model size and number of examples in-context hold for most tasks we study. We emphasize that these “learning” curves involve no gradient updates or fine-tuning, just increasing numbers of demonstrations given as conditioning. Broadly, on NLP tasks GPT-3 achieves promising results in the zero-shot and one-shot settings, and in the the few-shot setting is sometimes competitive with or even occasionally surpasses state-of-the-art (despite state-of-the-art being held by fine-tuned models). For example, GPT-3 achieves 81.5 F1 on CoQA in the zero-shot setting, 84.0 F1 on CoQA in the one-shot setting, 85.0 F1 in the few-shot setting. Similarly, GPT-3 achieves 64.3% accuracy on TriviaQA in the zero-shot setting, 68.0% in the one-shot setting, and 71.2% in the few-shot setting, the last of which is state-of-the

[2] brown-2020-gpt3.pdf / brown-2020-gpt3-0029
PP+20]. GPT-3’s few-shot result further improves performance another 3.2% beyond this. On WebQuestions (WebQs), GPT-3 achieves 14.4% in the zero-shot setting, 25.3% in the one-shot setting, and 41.5% in the few-shot setting. This compares to 37.4% for fine-tuned T5-11B, and 44.7% for fine-tuned T5-11B+SSM, which uses a Q&A-specific pre-training procedure. GPT-3 in the few-shot setting approaches the performance of state-of-the-art fine-tuned models. Notably, compared to TriviaQA, WebQS shows a much larger gain from zero-shot to few-shot (and indeed its zero-shot and one-shot performance are poor), perhaps suggesting that the WebQs questions 13 [page=14] Figure 3.3: On TriviaQA GPT3’s performance grows smoothly with model size, suggesting that language models continue to absorb knowledge as their capacity increases. One-shot and few-shot performance make significant gains over zero-shot behavior, matching and exceeding the performance of the SOTA fine-tuned open-domain model, RAG [LPP+20] and/or the style of their answers are out-of-distribution for GPT-3. Nevertheless, GPT-3 appears able to adapt to this distribution, recovering strong performance in the few-shot setting. On Natural Questions (NQs) GPT-3 achieves 14.6% in the zero-shot setting, 23.0% in the one-shot setting, and 29.9% in the few-shot setting, compared to 36.6% for fine-tuned T5 11B+SSM. Similar to WebQS, the large gain from zero-shot to few-shot may suggest a distribution shift, and may also explain the less competitive performance compared to TriviaQA and WebQS. In particular, the questions in NQs tend towards very fine-grained knowledge on Wikipedia specifically which could be testing the limits of GPT-3’s capacity and broad pretraining distribution. Overall, on one of the three datasets GPT-3’s one-shot matches the open-domain fine-tuning SOTA. On the other two datasets it approaches the performance of the

[3] brown-2020-gpt3.pdf / brown-2020-gpt3-0009

In [44]:
df_generacion = pd.DataFrame(resultados_generacion)

display(df_generacion[
    [
        "pregunta",
        "respuesta",
        "abstencion",
        "generador"
    ]
])

,pregunta,respuesta,abstencion,generador
0,What are the main advantages of the Transforme...,[modo inspección: no hay clave de API ni Ollam...,None,modo inspección (sin clave ni Ollama)
1,How does GPT-3 demonstrate that increasing mod...,[modo inspección: no hay clave de API ni Ollam...,None,modo inspección (sin clave ni Ollama)
2,How does InstructGPT use human feedback to imp...,[modo inspección: no hay clave de API ni Ollam...,None,modo inspección (sin clave ni Ollama)

In [45]:
archivo_generacion = carpeta_resultados / "numeral5_generacion.csv"

df_generacion.to_csv(
    archivo_generacion,
    index=False,
    encoding="utf-8-sig"
)

print(f"Guardado en: {archivo_generacion}")

Guardado en: /home/dludena/taller-02-rag-alvarez-ballesteros-ludena/resultados/parte1/numeral5_generacion.csv

In [46]:
salidas_generacion = []

for pregunta in preguntas_prueba:

    resultado = pipeline.answer(
        pregunta,
        top_k=5
    )

    salidas_generacion.append(resultado)

archivo_generacion_json = carpeta_resultados / "numeral5_generacion.json"

with open(
    archivo_generacion_json,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        salidas_generacion,
        f,
        ensure_ascii=False,
        indent=2
    )

print(f"Guardado en: {archivo_generacion_json}")

Guardado en: /home/dludena/taller-02-rag-alvarez-ballesteros-ludena/resultados/parte1/numeral5_generacion.json